### ISSUE TITLE
Questions about inference camera views

### ISSUE THREAD

**Issue by anjagjerpe** [mdcrosby/animal-ai#1]
Hi! 

Figured this would be the most effective place to ask. 

I'm doing inference on a trained agent (separately trained in PyTorch just using the `AnimalAIEnvironment` class, so moving the model back into the Unity editor is a bit difficult), and I wish to view the environment from either bird-eye or third person rather than though the agent. Is it possible to switch the camera during inference like you can in play mode? This might also be nice to have available in the environment state space in the future. 

I see it's possible switch camera view in the 'Play and Watch' demo on the competition website. Is the code for that available? 

Thank you in advance!

**Comment by mdcrosby** [comment]
This is a good feature request. It's on the ToDo list. Currently 2.3 has planned a lot of features to help with analysing agent behaviour so I'll add it to that.

The web version on animalaiolympics.com is separate from both 2.0 and this Beta and discontinued in terms of development. However, our roadmap includes creating a new version of the web version with all the old features (and more) and it will be possible to replay agents there. (It will also be possible to do this offline by then anyway).
