### ISSUE TITLE
Environment timed out

### ISSUE THREAD

**Issue by jd730** [mdcrosby/animal-ai#2]
Hi,

Thank you for improving the Animal-AI testbed. while testing `gymwrapper.py` I received the below error. Could you help me with how to deal with this? Version of my `mlagents_envs` is 0.27.0.

Thank you so much!

```
[WARNING] Environment timed out shutting down. Killing...
Traceback (most recent call last):
  File "gymwrapper.py", line 68, in <module>
    train_agent_single_config(configuration_file=configuration_file)
  File "gymwrapper.py", line 31, in train_agent_single_config
    captureFrameRate = captureFrameRate, #Set this so the output on screen is visible - set to 0 for faster training but no visual updates
  File "/home/jdhwang/animal-ai/animalai/envs/environment.py", line 95, in __init__
    log_folder=log_folder,
  File "/om2/user/jdhwang/anaconda3/envs/myenv/lib/python3.7/site-packages/mlagents_envs/environment.py", line 223, in __init__
    aca_output = self._send_academy_parameters(rl_init_parameters_in)
  File "/om2/user/jdhwang/anaconda3/envs/myenv/lib/python3.7/site-packages/mlagents_envs/environment.py", line 477, in _send_academy_parameters
    return self._communicator.initialize(inputs, self._poll_process)
  File "/om2/user/jdhwang/anaconda3/envs/myenv/lib/python3.7/site-packages/mlagents_envs/rpc_communicator.py", line 121, in initialize
    self.poll_for_timeout(poll_callback)
  File "/om2/user/jdhwang/anaconda3/envs/myenv/lib/python3.7/site-packages/mlagents_envs/rpc_communicator.py", line 112, in poll_for_timeout
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Agents' Behavior Parameters > Behavior Type is set to "Default"
         The environment and the Python interface have compatible versions.
```

**Comment by mdcrosby** [comment]
Hi,

 Could you confirm that this is with env v2.2.3 and also mlagents==0.27.0 and gym-unity==0.27.0 also installed? Does play.py work as expected?

**Comment by jd730** [comment]
Hi @mdcrosby, Thank you for the fast reply.

I am using `https://www.doc.ic.ac.uk/~mcrosby/aai_builds/AnimalAI_LINUX_2.2.3.zip` and both mlagents and gym-unity is 0.27.0.
`play.py` also doesn't work with the same error.

For your information, I am using CentOS 7.

**Comment by mdcrosby** [comment]
Thanks. Unfortunately I only have a set up to test on Ubuntu at the moment. We've had issues reported for CentOS before. The Player.Log file might have some extra information. You can find it at `~/.config/unity3d/MaCroAI/AnimalAI/Player.log`.

**Comment by mdcrosby** [comment]
Not sure if this helps, but the previous CentOS issues were with Unity and OpenGL and were solved using a remote desktop (FastX) and VirtualGL.

**Comment by jd730** [comment]
The log shows that 

```
Mono path[0] = '/home/jdhwang/animal-ai/env/AnimalAI_Data/Managed'
Mono config path = '/home/jdhwang/animal-ai/env/AnimalAI_Data/MonoBleedingEdge/etc'
Preloaded 'lib_burst_generated.so'
Preloaded 'libgrpc_csharp_ext.x64.so'
Unable to load player prefs
Desktop is 0 x 0 @ 0 Hz
Invalid initial resolution 80 x 80 - forcing to 100 x 100
```

I will take a look FastX and VirtualGL and let you know whether it can solve the problem or not.

**Comment by mdcrosby** [comment]
Don't worry about the last line, but the preceding one suggests that Unity doesn't have a display to connect to. Hopefully sorting that will fix your problem.

**Comment by jd730** [comment]
@mdcrosby  I can run `play.py` with FastX3 and VGL after downgrading mlagents to 0.26.0.

Would it be possible to not visualize while training?

Thank you so much.

**Comment by mdcrosby** [comment]
Unfortunately not. Unity needs access to a (possibly virtual) display to be able to provide visual observations. It's possible to train headless on environments without visual observations ([e.g. see here](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Executable.md)), but we don't support that for AAI given the nature of the environment.

(Sorry, I should have mentioned before that the current version uses ml-agents 0.26.0 - the next release will use 0.27.0.)
