### ISSUE TITLE
How is the competition preparation going on?

### ISSUE THREAD

**Issue by ghost** [mdcrosby/animal-ai#5]
I post this here, cause there is no contact [here](http://www.animalaiolympics.com/AAI/).
On the page, there's a coming competition in 2021, though 2021 is almost gone.
Would you kindly share any updates for this environment and competition?

I also hope to have comprehensive documentation for AninalAI, it is hard to use version 3 without refering version 2.

**Comment by mdcrosby** [comment]
Hi. Unfortunately any competition plans had to be put on hold. I'm no longer working on this project. I'm not sure what the plans are for the future from others that are taking over.

**Comment by ghost** [comment]
Thanks for letting me know! Hope to have competition again!
