### ISSUE TITLE
Missing Environment Download Link

### ISSUE THREAD

**Issue by shibukazu** [mdcrosby/animal-ai#9]
Hi, developer.
I'm trying to download animal-ai environment from the link below.
http://mdcrosby.com/builds/AnimalAI_MAC_3.0.zip
But, It looks like the link has been expired.
Could anyone fix this problem?
Thanks.

**Comment by pkuderov** [comment]
+1 to the request

@mdcrosby could you please re-upload somewhere the missing archives as a quick fix at least?

Thanks

**Comment by pkuderov** [comment]
@thanksphil I'm sorry for the direct tagging, but maybe you can help us here? Sadly, this issue is a real stopper.

**Comment by kozzy97** [comment]
Hi, sorry for the slow response on our front. Please find the new links below:

[Linux](https://kv301.user.srcf.net/wp-content/uploads/2022/04/AAI_v3.0.1_build_linux_090422.zip)
[MacOS](https://kv301.user.srcf.net/wp-content/uploads/2022/04/AAI_v3.0.1_build_macOS_090422.zip)
[Windows](https://kv301.user.srcf.net/wp-content/uploads/2022/04/AAI_v3.0.1_build_windows_090422.zip)

Please note, this is version 3.0.1. The only addition is an optional parameter to freeze the agent for a specified number of frames at the start of an episode, with no reward penalty.

I've created a pull request for the repo to be updated with these.

**Comment by kozzy97** [comment]
The repo has been updated, so I'll close this issue.
